version: "2"

services:
  
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./php/public:/srv/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - nodejs

  nodejs:
    image: node:alpine
    environment: 
      NODE_ENV: production
    working_dir: /home/app
    restart: always
    volumes:
      - ./nodejs:/home/app
    depends_on:
      - php
    command: ["node", "index"]

  php:
    image: php:apache
    volumes:
      - ./php:/var/www/html